"""Generate kb/INDEX.md and kb/rubric.md from principle frontmatter.

Generated files are committed; CI regenerates them and fails on any diff.
INDEX.md is one line per principle and per pattern, at most 200 lines.

    python -m henriquefy.ingest.build_index [--check]
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

from henriquefy.check.rules import RULES
from henriquefy.paths import kb_dir

CATEGORIES = ("modeling", "simplicity", "errors", "testing", "api", "project", "readability")
DIMENSIONS = {
    "modeling": "Modelagem",
    "simplicity": "Simplicidade",
    "errors": "Erros",
    "testing": "Testes",
    "api": "API",
    "project": "Projeto e config",
    "readability": "Legibilidade",
}
INDEX_BUDGET = 200


def frontmatter(path: Path) -> dict[str, str]:
    m = re.match(r"---\n(.*?)\n---\n", path.read_text(encoding="utf-8"), re.S)
    if not m:
        raise ValueError(f"{path}: no frontmatter")
    fields = {}
    for line in m.group(1).splitlines():
        if line and not line.startswith(" ") and ":" in line:
            key, _, value = line.partition(":")
            fields[key.strip()] = value.split("#", 1)[0].strip()
    return fields


def rule_line(path: Path) -> str:
    """The one-sentence rule: first sentence after `**Rule.**`."""
    text = path.read_text(encoding="utf-8")
    m = re.search(r"\*\*Rule\.\*\*\s*(.+?)(?<=[.!?])\s", text, re.S)
    if not m:
        raise ValueError(f"{path}: no **Rule.** paragraph")
    return re.sub(r"\s+", " ", m.group(1)).strip()


def entries(folder: Path) -> list[Path]:
    return sorted(p for p in folder.glob("*.md") if not p.name.startswith("_"))


def build_index(kb: Path) -> str:
    lines = [
        "# henriquefy knowledge base index",
        "",
        "Generated by `build_index.py`; do not edit. One line per principle:"
        " `id | category | detectable | rule`, and per pattern: `id | principle | frameworks`."
        " Open `principles/<id>.md` or `patterns/<id>.md` for the full entry.",
        "",
        "## Principles",
        "",
    ]
    for p in entries(kb / "principles"):
        fm = frontmatter(p)
        lines.append(f"- {fm['id']} | {fm['category']} | {fm['detectable']} | {rule_line(p)}")
    lines += ["", "## Patterns", ""]
    for p in entries(kb / "patterns"):
        fm = frontmatter(p)
        text = p.read_text(encoding="utf-8")
        fws = ", ".join(re.findall(r"^\s{2}(python|django|fastapi):", text, re.M))
        lines.append(f"- {fm['id']} | {fm['principle']} | {fws}")
    lines += ["", "## Courses", ""]
    for c in entries(kb / "courses"):
        if c.name == "README.md":
            continue
        title = re.search(r"^# (.+)$", c.read_text(encoding="utf-8"), re.M)
        lines.append(f"- {c.stem} | {title.group(1) if title else c.stem}")
    out = "\n".join(lines) + "\n"
    if len(lines) > INDEX_BUDGET:
        raise SystemExit(f"INDEX.md would be {len(lines)} lines; budget is {INDEX_BUDGET}")
    return out


def build_rubric(kb: Path) -> str:
    weights: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    for p in entries(kb / "principles"):
        fm = frontmatter(p)
        if fm["category"] in CATEGORIES:
            weights[fm["category"]].append((fm["id"], int(fm["weight"]), fm["detectable"]))
    lines = [
        "# Rubric",
        "",
        "Generated by `build_index.py` from principle frontmatter; do not edit.",
        "",
        "Seven dimensions, each 0 to 10. A dimension's weight in the overall is the sum of the"
        " weights of its principles. A dimension with no evidence in the target is N/A and left"
        " out. The Nota mecânica uses only principles marked `mechanical` or `partial`; the Nota"
        " do Henrique uses all of them.",
        "",
        "| dimension | category | weight | principles (weight, detectable) |",
        "|---|---|---|---|",
    ]
    for cat in CATEGORIES:
        items = weights.get(cat, [])
        total = sum(w for _, w, _ in items)
        listed = ", ".join(f"{i} ({w}, {d})" for i, w, d in items) or "none yet"
        lines.append(f"| {DIMENSIONS[cat]} | {cat} | {total} | {listed} |")
    lines += [
        "",
        "Nota mecânica formula: penalty(principle) = min(1, 2 * findings / files scanned);"
        " penalty(dimension) = weighted mean over its mechanical and partial principles whose"
        " rules were applicable; score(dimension) = 10 * (1 - penalty), one decimal; overall ="
        " weighted mean of the scored dimensions. Judgment-only principles never enter this"
        " number. The formula lives here so it can be read, not inferred.",
    ]
    return "\n".join(lines) + "\n"


def build_check_rules(kb: Path) -> str:
    known = {p.stem for p in entries(kb / "principles")}
    lines = [
        "# Check rules",
        "",
        "Generated by `build_index.py` from `henriquefy.check.rules`; do not edit. Every mechanical"
        " rule maps to one principle; suppress a finding with `# henriquefy: ignore[rule-id]` on"
        " the line or the line above.",
        "",
        "| rule | principle | scope | fires on | fix |",
        "|---|---|---|---|---|",
    ]
    for r in RULES.values():
        if r.principle not in known:
            raise SystemExit(f"rule {r.id} maps to unknown principle {r.principle}")
        lines.append(f"| `{r.id}` | {r.principle} | {r.scope} | {r.detect} | {r.fix} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    kb = kb_dir()
    outputs = {
        kb / "INDEX.md": build_index(kb),
        kb / "rubric.md": build_rubric(kb),
        kb / "check-rules.md": build_check_rules(kb),
    }
    if "--check" in argv:
        stale = [p.name for p, text in outputs.items() if not p.is_file() or p.read_text() != text]
        if stale:
            print(f"stale generated files: {', '.join(stale)}; run build_index", file=sys.stderr)
            return 1
        print("generated files up to date")
        return 0
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8")
        print(f"wrote {p.relative_to(kb.parent)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
